#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a configuration file for the redirection
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx to apply changes
sudo service nginx restart

