#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Create a configuration file for the custom 404 page
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        return 404;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx to apply changes
sudo service nginx restart

