#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.

# Check if an IP address is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the first argument
IP="$1"

# Ping the IP address 5 times
ping -c 5 "$IP"

