#!/usr/bin/env bash
# Bash script that uses ssh to connect to

# Set the server IP address or hostname
server_address="54.172.249.133"

# Use the ssh command with single-character flags
ssh -i ~/.ssh/school ubuntu@$server_address
